import type { Metadata } from "next";
import { ApolloWrapper } from "./ApolloWrapper";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/tachyons@4.12.0/css/tachyons.min.css"
        />
      </head>
      <body
      >
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
