type Query {
    getAuthors(author_ids: [ID], emails: [String!], role: Role, usernames: [String!]): [Author!]!
    getPosts(post_ids: [ID!], author_ids: [ID!], titles: [String!], categories: [String!], published: Boolean, skip: Int, take: Int, order_by: PostOrderBy): Feed!
}

type Mutation {
    addPost(title: String!, content: String!, categories: [String!]!, published: Boolean): Post!
    deleteAuthor(author_id: ID, email: String): Author!
    deletePost(post_id: ID, title: String): Post!
    incrementPost(post_id: ID!, type: IncrementType!): Post!
    login(email: String!, password: String!): AuthPayload
    signup(email: String!, password: String!, first_name: String!, last_name: String!, username: String!): AuthPayload
    updateAuthor(author_id: ID!, first_name: String, last_name: String, email: String, role: Role, username: String): Author!
    updatePost(post_id: ID!, title: String, content: String, categories: [String!], published: Boolean): Post!
}

directive @auth(requires: Role = ADMIN) on FIELD_DEFINITION

type AuthPayload {
  token: String
  author: Author
}

type Author {
  author_id: ID!
  date_created: String!
  date_updated: String!
  posts: [Post!]
  username: String!

  # Protected fields
  email: String @auth(requires: ADMIN)
  password: String @auth(requires: ADMIN)
  first_name: String @auth(requires: ADMIN)
  last_name: String @auth(requires: ADMIN)
  role: Role @auth(requires: ADMIN)
}

type Feed {
  total: Int!
  items: [Post!]!
}

type Post {
  post_id: ID!
  author: Author!
  author_id: ID!
  categories: [String!]!
  content: String!
  date_created: String!
  date_updated: String!
  likes: Int
  published: Boolean!
  shares: Int
  title: String!
  views: Int
}

input PostOrderBy {
  date_created: Sort
  date_updated: Sort
  likes: Sort
  shares: Sort
  title: Sort
  views: Sort
}

enum IncrementType {
  LIKE
  SHARE
  VIEW
}

enum Role {
  ADMIN
  AUTHOR
}

enum Sort {
  asc
  desc
}