type Query {
    getAllPosts: [Post!]!
    getPosts(ids: [ID], titles: [String!], categories: [String!]): [Post!]!
}

type Mutation {
    addPost(title: String!, content: String!, categories: [String!]!, published: Boolean): Post!
    deletePost(id: ID!): Post!
    updatePost(id: ID!, title: String, content: String, categories: [String!], published: Boolean): Post!
}

type Post {
  id: ID!
  categories: [String!]!
  content: String!
  createdAt: String!
  published: Boolean!
  title: String!
  updatedAt: String
}