type Query {
    getAllPosts: [Post!]!
    getAllAuthors: [Author!]!
    getAuthors(ids: [ID], emails: [String!], role: Role, usernames: [String!]): [Author!]!
    getPosts(ids: [ID], titles: [String!], categories: [String!]): [Post!]!
}

type Mutation {
    addPost(title: String!, content: String!, categories: [String!]!, published: Boolean): Post!
    deleteAuthor(id: ID, email: String): Author!
    deletePost(id: ID, title: String): Post!
    incrementPost(id: ID!, type: IncrementType!): Post!
    login(email: String!, password: String!): AuthPayload
    signup(email: String!, password: String!, first_name: String!, last_name: String!, username: String!): AuthPayload
    updateAuthor(id: ID!, first_name: String, last_name: String, email: String, role: Role, username: String): Author!
    updatePost(id: ID!, title: String, content: String, categories: [String!], published: Boolean): Post!
}

type AuthPayload {
  token: String
  author: Author
}

type Author {
  id: ID!
  createdAt: String!
  email: String!
  first_name: String!
  last_name: String!
  password: String!
  posts: [Post!]!
  role: Role!
  updatedAt: String
  username: String!
}

type Post {
  id: ID!
  author: Author!
  authorId: ID!
  categories: [String!]!
  content: String!
  createdAt: String!
  likes: Int
  published: Boolean!
  shares: Int
  title: String!
  updatedAt: String
  views: Int
}

enum IncrementType {
  LIKE
  SHARE
  VIEW
}

enum Role {
  ADMIN
  AUTHOR
}
